[2023-08-19 14:02:16,649][turingmirror.utils.log][INFO] - Git sha: 8f073c0d79ce2a41ed1853786d4edefff4386c67
[2023-08-19 14:02:16,653][__main__][INFO] - /home/jason/dev/acs/TuringMirror/data/fables/model.name=gpt-3.5-turbo
[2023-08-19 14:12:47,612][langchain.chat_models.openai][WARNING] - Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
[2023-08-19 14:28:50,034][langchain.chat_models.openai][WARNING] - Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
[2023-08-19 14:32:08,444][__main__][ERROR] - id: 83, exception: Unterminated string starting at: line 1 column 11 (char 10)
Traceback (most recent call last):
  File "/home/jason/dev/acs/TuringMirror/turingmirror/scripts/generate_new_fable_from_moral.py", line 95, in generate_new_fable
    return find_and_parse_json_block(extracted_fable_json)["fable"]
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/interlab/queries/json_parsing.py", line 40, in find_and_parse_json_block
    raise e
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/interlab/queries/json_parsing.py", line 30, in find_and_parse_json_block
    return dirtyjson.loads(m.groups()[-1])
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/__init__.py", line 94, in loads
    return d.decode(search_for_first_object, start_index)
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/loader.py", line 372, in decode
    obj = self.scan()
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/loader.py", line 173, in scan
    return self.parse_object()
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/loader.py", line 318, in parse_object
    value = self.scan()
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/loader.py", line 171, in scan
    return self.parse_string(nextchar)
  File "/home/jason/dev/acs/TuringMirror/.venv/lib/python3.10/site-packages/dirtyjson/loader.py", line 226, in parse_string
    raise Error(
dirtyjson.error.Error: Unterminated string starting at: line 1 column 11 (char 10)
[2023-08-19 14:42:21,661][langchain.chat_models.openai][WARNING] - Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
